import { ValidationField } from '../store/useAppStore';

export type PDFTemplateType = 'corporate' | 'financial' | 'grid';

export interface PDFTemplateOptions {
    title: string;
    subtitle?: string;
    logo?: string; // Base64 or URL
    color?: string;
}

/**
 * Service to manage professional PDF templates for extraction reports.
 * Provides high-fidelity HTML/CSS layouts optimized for PDF generation.
 */
export class PDFTemplateService {
    /**
     * Generate HTML for a specific template type.
     */
    static getTemplate(
        type: PDFTemplateType,
        fields: ValidationField[],
        options: PDFTemplateOptions
    ): string {
        const tableRows = this.buildTableRows(type, fields);
        const styles = this.getStyles(type, options.color || '#111827');
        const header = this.buildHeader(type, options);

        return `
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <style>${styles}</style>
</head>
<body>
    ${header}
    <table>
        ${this.buildTableHeader(type)}
        <tbody>
            ${tableRows}
        </tbody>
    </table>
    <div class="footer">
        Generated by EXELENT_OS · ${new Date().toLocaleString()} · System Page 1/1
    </div>
</body>
</html>`;
    }

    private static buildHeader(type: PDFTemplateType, options: PDFTemplateOptions): string {
        if (type === 'corporate') {
            return `
                <div class="header">
                    <div class="header-left">
                        <h1>${this.escapeHTML(options.title)}</h1>
                        <p class="subtitle">${this.escapeHTML(options.subtitle || 'Extraction Analysis Report')}</p>
                    </div>
                </div>
            `;
        }
        if (type === 'financial') {
            return `
                <div class="header financial-header">
                    <h1>[DATA_AUDIT_LOG]</h1>
                    <div class="meta-strip">
                        <span>TITLE: ${this.escapeHTML(options.title)}</span>
                        <span>DATE: ${new Date().toLocaleDateString()}</span>
                    </div>
                </div>
            `;
        }
        return `<h1>${this.escapeHTML(options.title)}</h1>`;
    }

    private static buildTableHeader(type: PDFTemplateType): string {
        if (type === 'financial') {
            return `
                <thead>
                    <tr>
                        <th style="width: 30%">ENTRY_KEY</th>
                        <th style="width: 40%">EXTRACTED_VALUE</th>
                        <th style="width: 15%">CONFIDENCE</th>
                        <th style="width: 15%">CLASS</th>
                    </tr>
                </thead>
            `;
        }
        return `
            <thead>
                <tr>
                    <th>Field</th>
                    <th>Value</th>
                    <th>Conf.</th>
                    <th>Category</th>
                </tr>
            </thead>
        `;
    }

    private static buildTableRows(type: PDFTemplateType, fields: ValidationField[]): string {
        return fields
            .map((f) => {
                const confColor = f.confidence >= 0.9 ? '#10B981' : f.confidence >= 0.7 ? '#F59E0B' : '#EF4444';
                const confText = `${Math.round(f.confidence * 100)}%`;

                if (type === 'financial') {
                    return `
                        <tr>
                            <td class="mono">${this.escapeHTML(f.label)}</td>
                            <td class="bold">${this.escapeHTML(f.value)}</td>
                            <td style="color: ${confColor}; font-family: monospace; font-weight: bold;">${confText}</td>
                            <td><span class="pill">${this.escapeHTML(f.category || 'N/A')}</span></td>
                        </tr>
                    `;
                }

                return `
                    <tr>
                        <td class="label-cell">${this.escapeHTML(f.label)}</td>
                        <td class="value-cell">${this.escapeHTML(f.value)}</td>
                        <td class="conf-cell" style="color: ${confColor}">${confText}</td>
                        <td class="cat-cell">${this.escapeHTML(f.category || '')}</td>
                    </tr>
                `;
            })
            .join('\n');
    }

    private static getStyles(type: PDFTemplateType, primaryColor: string): string {
        const baseStyles = `
            body { font-family: -apple-system, system-ui, sans-serif; margin: 40px; color: #111827; line-height: 1.4; }
            table { width: 100%; border-collapse: collapse; margin-top: 20px; }
            th { text-align: left; padding: 12px; font-size: 11px; text-transform: uppercase; letter-spacing: 0.05em; border-bottom: 2px solid #E5E7EB; color: #6B7280; }
            td { padding: 12px; border-bottom: 1px solid #F3F4F6; font-size: 13px; vertical-align: top; }
            .footer { position: fixed; bottom: 0; left: 0; right: 0; font-size: 10px; color: #9CA3AF; text-align: center; border-top: 1px solid #F3F4F6; padding-top: 10px; }
            .pill { background: #F3F4F6; padding: 2px 8px; border-radius: 4px; font-size: 10px; font-weight: 600; color: #4B5563; }
        `;

        if (type === 'corporate') {
            return baseStyles + `
                h1 { font-size: 28px; margin: 0; color: ${primaryColor}; }
                .subtitle { font-size: 14px; color: #6B7280; margin: 4px 0 0 0; }
                .header { margin-bottom: 40px; border-bottom: 1px solid #E5E7EB; padding-bottom: 20px; }
                th { background: #F9FAFB; }
                .label-cell { font-weight: 600; width: 30%; }
                .value-cell { width: 40%; }
                .conf-cell { font-weight: 700; width: 10%; text-align: right; }
                .cat-cell { width: 20%; color: #6B7280; }
            `;
        }

        if (type === 'financial') {
            return baseStyles + `
                body { background-color: #ffffff; }
                h1 { font-family: monospace; font-size: 20px; letter-spacing: 2px; margin: 0; }
                .financial-header { background: #111827; color: white; padding: 20px; margin: -40px -40px 40px -40px; }
                .meta-strip { margin-top: 10px; font-family: monospace; font-size: 10px; display: flex; gap: 20px; opacity: 0.8; }
                th { background: #F3F4F6; border: 1px solid #D1D5DB; color: #111827; font-weight: 800; }
                td { border: 1px solid #E5E7EB; font-family: sans-serif; }
                .mono { font-family: monospace; font-size: 11px; color: #4B5563; }
                .bold { font-weight: 700; color: #000; }
            `;
        }

        return baseStyles + `
            h1 { font-size: 24px; text-align: center; margin-bottom: 30px; }
            tr:nth-child(even) { background-color: #F9FAFB; }
        `;
    }

    private static escapeHTML(str: string): string {
        return str
            .replace(/&/g, '&amp;')
            .replace(/</g, '&lt;')
            .replace(/>/g, '&gt;')
            .replace(/"/g, '&quot;');
    }
}
